import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Landing from "~/components/landing";
import Nav from "~/components/nav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-white">
        <Nav/>
        <Landing/>
      </main>
    </>
  );
};

export default Home;
